repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff check
        entry: uv run ruff check
        language: system
        types: [python]
      - id: mypy
        name: mypy
        entry: uv run mypy
        language: system
        types: [python]
      - id: pytest
        name: pytest
        entry: uv run pytest
        language: system
        types: [python]
        always_run: true
        pass_filenames: false
